### ISSUE TITLE
系统重启会重新初始化布隆过滤器之前的数据吗？

### ISSUE THREAD

**Issue by cmzdandan** [wxisme/bloomfilter#3]
我们在系统初始化的时候创建布隆过滤器
        BloomFilter<String> filter = new BloomFilter<String>(0.0001, 10000);
        Jedis jedis = new Jedis("127.0.0.1", 6379);
        jedis.auth("1234");
        filter.bind(new RedisBitSet(jedis, "bloomfilter:key:name"));
想请问，系统之前启动过，那么redis中已经有一个key叫：bloomfilter:key:name
如果系统重启，之前的key为bloomfilter:key:name的数据还在吗？如果数据会被清理掉，那么怎么样可以做到继续用这个key名字而数据沿用之前的数据呢？
谢谢！

**Comment by wangxu0** [comment]
First of all, I can answer you in Chinese, but I prefer to answer in English. As you know, Redis is an in-memory database, so when you reboot the system, all the data will be discarded. However, Redis has some persistence mechanisms such as RDB and AOF. If you don't have any configuration, Redis should have RDB persistence by default, which means that Redis will load the persistent data into memory after the system restarts. If so, you can continue to use this bloomfilter.
I recommend you read the documentation: [Chinese](http://redis.cn/topics/persistence.html)  [English](https://redis.io/topics/persistence)
